    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set-opaque
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the job_list_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

/* temp-job-list-accessors.c */
unsigned long job_list_get_count(job_list_t *job_list_ptr);
job_t *job_list_get_jobs_ae(job_list_t *job_list_ptr, size_t c);
