    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set-transparent
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the job_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define JOB_JOBID(ptr)                  ((ptr)->jobid)
#define JOB_SCRIPT_PATH(ptr)            ((ptr)->script_path)
#define JOB_SCRIPT_PATH_AE(ptr,c)       ((ptr)->script_path[c])
#define JOB_WORKING_DIRECTORY(ptr)      ((ptr)->working_directory)
#define JOB_WORKING_DIRECTORY_AE(ptr,c) ((ptr)->working_directory[c])
#define JOB_USER_NAME(ptr)              ((ptr)->user_name)
#define JOB_USER_NAME_AE(ptr,c)         ((ptr)->user_name[c])
#define JOB_JOBS(ptr)                   ((ptr)->jobs)
#define JOB_CORES_PER_JOB(ptr)          ((ptr)->cores_per_job)
#define JOB_CORES_PER_NODE(ptr)         ((ptr)->cores_per_node)
#define JOB_MEM_PER_CORE(ptr)           ((ptr)->mem_per_core)
