/***************************************************************************
 *  This file is automatically generated by gen-get-set.  Be sure to keep
 *  track of any manual changes.
 *
 *  These generated functions are not expected to be perfect.  Check and
 *  edit as needed before adding to your code.
 ***************************************************************************/

#include <string.h>
#include <ctype.h>
#include <stdbool.h>        // In case of bool
#include <stdint.h>         // In case of int64_t, etc
#include <xtend/string.h>   // strlcpy() on Linux
#include "job-private.h"


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Accessor for job_id member in a job_t structure.
 *      Use this function to get job_id in a job_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member job_id.
 *
 *  Examples:
 *      job_t           job;
 *      unsigned long   job_id;
 *
 *      job_id = job_get_job_id(&job);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-03-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

unsigned long    job_get_job_id(job_t *job_ptr)

{
    return job_ptr->job_id;
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Accessor for job_count member in a job_t structure.
 *      Use this function to get job_count in a job_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member job_count.
 *
 *  Examples:
 *      job_t           job;
 *      unsigned        job_count;
 *
 *      job_count = job_get_job_count(&job);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-03-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

unsigned    job_get_job_count(job_t *job_ptr)

{
    return job_ptr->job_count;
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Accessor for cores_per_job member in a job_t structure.
 *      Use this function to get cores_per_job in a job_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member cores_per_job.
 *
 *  Examples:
 *      job_t           job;
 *      unsigned        cores_per_job;
 *
 *      cores_per_job = job_get_cores_per_job(&job);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-03-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

unsigned    job_get_cores_per_job(job_t *job_ptr)

{
    return job_ptr->cores_per_job;
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Accessor for min_cores_per_node member in a job_t structure.
 *      Use this function to get min_cores_per_node in a job_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member min_cores_per_node.
 *
 *  Examples:
 *      job_t           job;
 *      unsigned        min_cores_per_node;
 *
 *      min_cores_per_node = job_get_min_cores_per_node(&job);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-03-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

unsigned    job_get_min_cores_per_node(job_t *job_ptr)

{
    return job_ptr->min_cores_per_node;
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Accessor for mem_per_core member in a job_t structure.
 *      Use this function to get mem_per_core in a job_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member mem_per_core.
 *
 *  Examples:
 *      job_t           job;
 *      size_t          mem_per_core;
 *
 *      mem_per_core = job_get_mem_per_core(&job);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-03-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

size_t    job_get_mem_per_core(job_t *job_ptr)

{
    return job_ptr->mem_per_core;
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Accessor for user_name member in a job_t structure.
 *      Use this function to get user_name in a job_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member user_name.
 *
 *  Examples:
 *      job_t           job;
 *      char *          user_name;
 *
 *      user_name = job_get_user_name(&job);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-03-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

char *    job_get_user_name(job_t *job_ptr)

{
    return job_ptr->user_name;
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Accessor for an array element of user_name member in a job_t
 *      structure. Use this function to get job_ptr->user_name[c]
 *      in a job_t object from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to get
 *      c               Subscript to the user_name array
 *
 *  Returns:
 *      Value of one element of structure member user_name.
 *
 *  Examples:
 *      job_t           job;
 *      size_t          c;
 *      char *          user_name_element;
 *
 *      user_name_element = job_get_user_name_ae(&job, c);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-03-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

char  job_get_user_name_ae(job_t *job_ptr, size_t c)

{
    return job_ptr->user_name[c];
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Accessor for working_directory member in a job_t structure.
 *      Use this function to get working_directory in a job_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member working_directory.
 *
 *  Examples:
 *      job_t           job;
 *      char *          working_directory;
 *
 *      working_directory = job_get_working_directory(&job);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-03-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

char *    job_get_working_directory(job_t *job_ptr)

{
    return job_ptr->working_directory;
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Accessor for an array element of working_directory member in a job_t
 *      structure. Use this function to get job_ptr->working_directory[c]
 *      in a job_t object from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to get
 *      c               Subscript to the working_directory array
 *
 *  Returns:
 *      Value of one element of structure member working_directory.
 *
 *  Examples:
 *      job_t           job;
 *      size_t          c;
 *      char *          working_directory_element;
 *
 *      working_directory_element = job_get_working_directory_ae(&job, c);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-03-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

char  job_get_working_directory_ae(job_t *job_ptr, size_t c)

{
    return job_ptr->working_directory[c];
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Accessor for script_name member in a job_t structure.
 *      Use this function to get script_name in a job_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member script_name.
 *
 *  Examples:
 *      job_t           job;
 *      char *          script_name;
 *
 *      script_name = job_get_script_name(&job);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-03-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

char *    job_get_script_name(job_t *job_ptr)

{
    return job_ptr->script_name;
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Accessor for an array element of script_name member in a job_t
 *      structure. Use this function to get job_ptr->script_name[c]
 *      in a job_t object from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to get
 *      c               Subscript to the script_name array
 *
 *  Returns:
 *      Value of one element of structure member script_name.
 *
 *  Examples:
 *      job_t           job;
 *      size_t          c;
 *      char *          script_name_element;
 *
 *      script_name_element = job_get_script_name_ae(&job, c);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-03-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

char  job_get_script_name_ae(job_t *job_ptr, size_t c)

{
    return job_ptr->script_name[c];
}
