/***************************************************************************
 *  This file is automatically generated by gen-get-set.  Be sure to keep
 *  track of any manual changes.
 *
 *  These generated functions are not expected to be perfect.  Check and
 *  edit as needed before adding to your code.
 ***************************************************************************/

#include <string.h>
#include <ctype.h>
#include <stdbool.h>        // In case of bool
#include <stdint.h>         // In case of int64_t, etc
#include <xtend/string.h>   // strlcpy() on Linux
#include "job-list-private.h"


/***************************************************************************
 *  Library:
 *      #include <job-list.h>
 *      
 *
 *  Description:
 *      Accessor for count member in a job_list_t structure.
 *      Use this function to get count in a job_list_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      job_list_ptr    Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member count.
 *
 *  Examples:
 *      job_list_t      job_list;
 *      unsigned long   count;
 *
 *      count = job_list_get_count(&job_list);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-04-28  gen-get-set Auto-generated from job-list-private.h
 ***************************************************************************/

unsigned long    job_list_get_count(job_list_t *job_list_ptr)

{
    return job_list_ptr->count;
}


/***************************************************************************
 *  Library:
 *      #include <job-list.h>
 *      
 *
 *  Description:
 *      Accessor for an array element of jobs member in a job_list_t
 *      structure. Use this function to get job_list_ptr->jobs[c]
 *      in a job_list_t object from non-member functions.
 *
 *  Arguments:
 *      job_list_ptr    Pointer to the structure to get
 *      c               Subscript to the jobs array
 *
 *  Returns:
 *      Value of one element of structure member jobs.
 *
 *  Examples:
 *      job_list_t      job_list;
 *      size_t          c;
 *      job_t *         jobs_element;
 *
 *      jobs_element = job_list_get_jobs_ae(&job_list, c);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-04-28  gen-get-set Auto-generated from job-list-private.h
 ***************************************************************************/

job_t  *job_list_get_jobs_ae(job_list_t *job_list_ptr, size_t c)

{
    return job_list_ptr->jobs[c];
}
