/***************************************************************************
 *  This file is automatically generated by gen-get-set.  Be sure to keep
 *  track of any manual changes.
 *
 *  These generated functions are not expected to be perfect.  Check and
 *  edit as needed before adding to your code.
 ***************************************************************************/

#include <string.h>
#include <ctype.h>
#include <stdbool.h>        // In case of bool
#include <stdint.h>         // In case of int64_t, etc
#include <xtend/string.h>   // strlcpy() on Linux
#include "job-private.h"


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for job_id member in a job_t structure.
 *      Use this function to set job_id in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      job_id is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_job_id      The new value for job_id
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      unsigned long   new_job_id;
 *
 *      if ( job_set_job_id(&job, new_job_id)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_job_id(job_t *job_ptr, unsigned long new_job_id)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->job_id = new_job_id;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for array_index member in a job_t structure.
 *      Use this function to set array_index in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      array_index is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_array_index The new value for array_index
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      unsigned long   new_array_index;
 *
 *      if ( job_set_array_index(&job, new_array_index)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_array_index(job_t *job_ptr, unsigned long new_array_index)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->array_index = new_array_index;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for job_count member in a job_t structure.
 *      Use this function to set job_count in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      job_count is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_job_count   The new value for job_count
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      unsigned        new_job_count;
 *
 *      if ( job_set_job_count(&job, new_job_count)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_job_count(job_t *job_ptr, unsigned new_job_count)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->job_count = new_job_count;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for procs_per_job member in a job_t structure.
 *      Use this function to set procs_per_job in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      procs_per_job is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_procs_per_job The new value for procs_per_job
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      unsigned        new_procs_per_job;
 *
 *      if ( job_set_procs_per_job(&job, new_procs_per_job)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_procs_per_job(job_t *job_ptr, unsigned new_procs_per_job)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->procs_per_job = new_procs_per_job;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for min_procs_per_node member in a job_t structure.
 *      Use this function to set min_procs_per_node in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      min_procs_per_node is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_min_procs_per_node The new value for min_procs_per_node
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      unsigned        new_min_procs_per_node;
 *
 *      if ( job_set_min_procs_per_node(&job, new_min_procs_per_node)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_min_procs_per_node(job_t *job_ptr, unsigned new_min_procs_per_node)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->min_procs_per_node = new_min_procs_per_node;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for mem_per_proc member in a job_t structure.
 *      Use this function to set mem_per_proc in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      mem_per_proc is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_mem_per_proc The new value for mem_per_proc
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      size_t          new_mem_per_proc;
 *
 *      if ( job_set_mem_per_proc(&job, new_mem_per_proc)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_mem_per_proc(job_t *job_ptr, size_t new_mem_per_proc)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->mem_per_proc = new_mem_per_proc;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for chaperone_pid member in a job_t structure.
 *      Use this function to set chaperone_pid in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      chaperone_pid is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_chaperone_pid The new value for chaperone_pid
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      pid_t           new_chaperone_pid;
 *
 *      if ( job_set_chaperone_pid(&job, new_chaperone_pid)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_chaperone_pid(job_t *job_ptr, pid_t new_chaperone_pid)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->chaperone_pid = new_chaperone_pid;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for job_pid member in a job_t structure.
 *      Use this function to set job_pid in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      job_pid is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_job_pid     The new value for job_pid
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      pid_t           new_job_pid;
 *
 *      if ( job_set_job_pid(&job, new_job_pid)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_job_pid(job_t *job_ptr, pid_t new_job_pid)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->job_pid = new_job_pid;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for dispatched member in a job_t structure.
 *      Use this function to set dispatched in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      dispatched is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_dispatched  The new value for dispatched
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      int             new_dispatched;
 *
 *      if ( job_set_dispatched(&job, new_dispatched)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_dispatched(job_t *job_ptr, int new_dispatched)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->dispatched = new_dispatched;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for user_name member in a job_t structure.
 *      Use this function to set user_name in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      user_name is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_user_name   The new value for user_name
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      char *          new_user_name;
 *
 *      if ( job_set_user_name(&job, new_user_name)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_user_name(job_t *job_ptr, char * new_user_name)

{
    if ( new_user_name == NULL )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->user_name = new_user_name;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for an array element of user_name member in a job_t
 *      structure. Use this function to set job_ptr->user_name[c]
 *      in a job_t object from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      c               Subscript to the user_name array
 *      new_user_name_element The new value for user_name[c]
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      size_t          c;
 *      char *          new_user_name_element;
 *
 *      if ( job_set_user_name_ae(&job, c, new_user_name_element)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      JOB_SET_USER_NAME_AE(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_user_name_ae(job_t *job_ptr, size_t c, char  new_user_name_element)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->user_name[c] = new_user_name_element;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for user_name member in a job_t structure.
 *      Use this function to set user_name in a job_t object
 *      from non-member functions.  This function copies the array pointed to
 *      by new_user_name to job_ptr->user_name.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_user_name   The new value for user_name
 *      array_size      Size of the user_name array.
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      char *          new_user_name;
 *      size_t          array_size;
 *
 *      if ( job_set_user_name_cpy(&job, new_user_name, array_size)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      JOB_SET_USER_NAME(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_user_name_cpy(job_t *job_ptr, char * new_user_name, size_t array_size)

{
    if ( new_user_name == NULL )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	// FIXME: Assuming char array is a null-terminated string
	strlcpy(job_ptr->user_name, new_user_name, array_size);
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for primary_group_name member in a job_t structure.
 *      Use this function to set primary_group_name in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      primary_group_name is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_primary_group_name The new value for primary_group_name
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      char *          new_primary_group_name;
 *
 *      if ( job_set_primary_group_name(&job, new_primary_group_name)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_primary_group_name(job_t *job_ptr, char * new_primary_group_name)

{
    if ( new_primary_group_name == NULL )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->primary_group_name = new_primary_group_name;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for an array element of primary_group_name member in a job_t
 *      structure. Use this function to set job_ptr->primary_group_name[c]
 *      in a job_t object from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      c               Subscript to the primary_group_name array
 *      new_primary_group_name_element The new value for primary_group_name[c]
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      size_t          c;
 *      char *          new_primary_group_name_element;
 *
 *      if ( job_set_primary_group_name_ae(&job, c, new_primary_group_name_element)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      JOB_SET_PRIMARY_GROUP_NAME_AE(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_primary_group_name_ae(job_t *job_ptr, size_t c, char  new_primary_group_name_element)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->primary_group_name[c] = new_primary_group_name_element;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for primary_group_name member in a job_t structure.
 *      Use this function to set primary_group_name in a job_t object
 *      from non-member functions.  This function copies the array pointed to
 *      by new_primary_group_name to job_ptr->primary_group_name.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_primary_group_name The new value for primary_group_name
 *      array_size      Size of the primary_group_name array.
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      char *          new_primary_group_name;
 *      size_t          array_size;
 *
 *      if ( job_set_primary_group_name_cpy(&job, new_primary_group_name, array_size)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      JOB_SET_PRIMARY_GROUP_NAME(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_primary_group_name_cpy(job_t *job_ptr, char * new_primary_group_name, size_t array_size)

{
    if ( new_primary_group_name == NULL )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	// FIXME: Assuming char array is a null-terminated string
	strlcpy(job_ptr->primary_group_name, new_primary_group_name, array_size);
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for submit_node member in a job_t structure.
 *      Use this function to set submit_node in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      submit_node is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_submit_node The new value for submit_node
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      char *          new_submit_node;
 *
 *      if ( job_set_submit_node(&job, new_submit_node)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_submit_node(job_t *job_ptr, char * new_submit_node)

{
    if ( new_submit_node == NULL )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->submit_node = new_submit_node;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for an array element of submit_node member in a job_t
 *      structure. Use this function to set job_ptr->submit_node[c]
 *      in a job_t object from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      c               Subscript to the submit_node array
 *      new_submit_node_element The new value for submit_node[c]
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      size_t          c;
 *      char *          new_submit_node_element;
 *
 *      if ( job_set_submit_node_ae(&job, c, new_submit_node_element)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      JOB_SET_SUBMIT_NODE_AE(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_submit_node_ae(job_t *job_ptr, size_t c, char  new_submit_node_element)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->submit_node[c] = new_submit_node_element;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for submit_node member in a job_t structure.
 *      Use this function to set submit_node in a job_t object
 *      from non-member functions.  This function copies the array pointed to
 *      by new_submit_node to job_ptr->submit_node.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_submit_node The new value for submit_node
 *      array_size      Size of the submit_node array.
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      char *          new_submit_node;
 *      size_t          array_size;
 *
 *      if ( job_set_submit_node_cpy(&job, new_submit_node, array_size)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      JOB_SET_SUBMIT_NODE(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_submit_node_cpy(job_t *job_ptr, char * new_submit_node, size_t array_size)

{
    if ( new_submit_node == NULL )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	// FIXME: Assuming char array is a null-terminated string
	strlcpy(job_ptr->submit_node, new_submit_node, array_size);
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for submit_directory member in a job_t structure.
 *      Use this function to set submit_directory in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      submit_directory is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_submit_directory The new value for submit_directory
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      char *          new_submit_directory;
 *
 *      if ( job_set_submit_directory(&job, new_submit_directory)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_submit_directory(job_t *job_ptr, char * new_submit_directory)

{
    if ( new_submit_directory == NULL )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->submit_directory = new_submit_directory;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for an array element of submit_directory member in a job_t
 *      structure. Use this function to set job_ptr->submit_directory[c]
 *      in a job_t object from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      c               Subscript to the submit_directory array
 *      new_submit_directory_element The new value for submit_directory[c]
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      size_t          c;
 *      char *          new_submit_directory_element;
 *
 *      if ( job_set_submit_directory_ae(&job, c, new_submit_directory_element)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      JOB_SET_SUBMIT_DIRECTORY_AE(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_submit_directory_ae(job_t *job_ptr, size_t c, char  new_submit_directory_element)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->submit_directory[c] = new_submit_directory_element;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for submit_directory member in a job_t structure.
 *      Use this function to set submit_directory in a job_t object
 *      from non-member functions.  This function copies the array pointed to
 *      by new_submit_directory to job_ptr->submit_directory.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_submit_directory The new value for submit_directory
 *      array_size      Size of the submit_directory array.
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      char *          new_submit_directory;
 *      size_t          array_size;
 *
 *      if ( job_set_submit_directory_cpy(&job, new_submit_directory, array_size)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      JOB_SET_SUBMIT_DIRECTORY(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_submit_directory_cpy(job_t *job_ptr, char * new_submit_directory, size_t array_size)

{
    if ( new_submit_directory == NULL )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	// FIXME: Assuming char array is a null-terminated string
	strlcpy(job_ptr->submit_directory, new_submit_directory, array_size);
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for script_name member in a job_t structure.
 *      Use this function to set script_name in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      script_name is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_script_name The new value for script_name
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      char *          new_script_name;
 *
 *      if ( job_set_script_name(&job, new_script_name)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_script_name(job_t *job_ptr, char * new_script_name)

{
    if ( new_script_name == NULL )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->script_name = new_script_name;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for an array element of script_name member in a job_t
 *      structure. Use this function to set job_ptr->script_name[c]
 *      in a job_t object from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      c               Subscript to the script_name array
 *      new_script_name_element The new value for script_name[c]
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      size_t          c;
 *      char *          new_script_name_element;
 *
 *      if ( job_set_script_name_ae(&job, c, new_script_name_element)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      JOB_SET_SCRIPT_NAME_AE(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_script_name_ae(job_t *job_ptr, size_t c, char  new_script_name_element)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->script_name[c] = new_script_name_element;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for script_name member in a job_t structure.
 *      Use this function to set script_name in a job_t object
 *      from non-member functions.  This function copies the array pointed to
 *      by new_script_name to job_ptr->script_name.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_script_name The new value for script_name
 *      array_size      Size of the script_name array.
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      char *          new_script_name;
 *      size_t          array_size;
 *
 *      if ( job_set_script_name_cpy(&job, new_script_name, array_size)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      JOB_SET_SCRIPT_NAME(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_script_name_cpy(job_t *job_ptr, char * new_script_name, size_t array_size)

{
    if ( new_script_name == NULL )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	// FIXME: Assuming char array is a null-terminated string
	strlcpy(job_ptr->script_name, new_script_name, array_size);
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for compute_node member in a job_t structure.
 *      Use this function to set compute_node in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      compute_node is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_compute_node The new value for compute_node
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      char *          new_compute_node;
 *
 *      if ( job_set_compute_node(&job, new_compute_node)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_compute_node(job_t *job_ptr, char * new_compute_node)

{
    if ( new_compute_node == NULL )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->compute_node = new_compute_node;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for an array element of compute_node member in a job_t
 *      structure. Use this function to set job_ptr->compute_node[c]
 *      in a job_t object from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      c               Subscript to the compute_node array
 *      new_compute_node_element The new value for compute_node[c]
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      size_t          c;
 *      char *          new_compute_node_element;
 *
 *      if ( job_set_compute_node_ae(&job, c, new_compute_node_element)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      JOB_SET_COMPUTE_NODE_AE(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_compute_node_ae(job_t *job_ptr, size_t c, char  new_compute_node_element)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->compute_node[c] = new_compute_node_element;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for compute_node member in a job_t structure.
 *      Use this function to set compute_node in a job_t object
 *      from non-member functions.  This function copies the array pointed to
 *      by new_compute_node to job_ptr->compute_node.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_compute_node The new value for compute_node
 *      array_size      Size of the compute_node array.
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      char *          new_compute_node;
 *      size_t          array_size;
 *
 *      if ( job_set_compute_node_cpy(&job, new_compute_node, array_size)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      JOB_SET_COMPUTE_NODE(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_compute_node_cpy(job_t *job_ptr, char * new_compute_node, size_t array_size)

{
    if ( new_compute_node == NULL )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	// FIXME: Assuming char array is a null-terminated string
	strlcpy(job_ptr->compute_node, new_compute_node, array_size);
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for push_command member in a job_t structure.
 *      Use this function to set push_command in a job_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      push_command is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_push_command The new value for push_command
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      char *          new_push_command;
 *
 *      if ( job_set_push_command(&job, new_push_command)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_push_command(job_t *job_ptr, char * new_push_command)

{
    if ( new_push_command == NULL )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->push_command = new_push_command;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for an array element of push_command member in a job_t
 *      structure. Use this function to set job_ptr->push_command[c]
 *      in a job_t object from non-member functions.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      c               Subscript to the push_command array
 *      new_push_command_element The new value for push_command[c]
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      size_t          c;
 *      char *          new_push_command_element;
 *
 *      if ( job_set_push_command_ae(&job, c, new_push_command_element)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      JOB_SET_PUSH_COMMAND_AE(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_push_command_ae(job_t *job_ptr, size_t c, char  new_push_command_element)

{
    if ( false )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	job_ptr->push_command[c] = new_push_command_element;
	return JOB_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <job.h>
 *      
 *
 *  Description:
 *      Mutator for push_command member in a job_t structure.
 *      Use this function to set push_command in a job_t object
 *      from non-member functions.  This function copies the array pointed to
 *      by new_push_command to job_ptr->push_command.
 *
 *  Arguments:
 *      job_ptr         Pointer to the structure to set
 *      new_push_command The new value for push_command
 *      array_size      Size of the push_command array.
 *
 *  Returns:
 *      JOB_DATA_OK if the new value is acceptable and assigned
 *      JOB_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      job_t           job;
 *      char *          new_push_command;
 *      size_t          array_size;
 *
 *      if ( job_set_push_command_cpy(&job, new_push_command, array_size)
 *              == JOB_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      JOB_SET_PUSH_COMMAND(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-05-06  gen-get-set Auto-generated from job-private.h
 ***************************************************************************/

int     job_set_push_command_cpy(job_t *job_ptr, char * new_push_command, size_t array_size)

{
    if ( new_push_command == NULL )
	return JOB_DATA_OUT_OF_RANGE;
    else
    {
	// FIXME: Assuming char array is a null-terminated string
	strlcpy(job_ptr->push_command, new_push_command, array_size);
	return JOB_DATA_OK;
    }
}
