node-list.o: node-list.c node-list.h node.h
	${CC} -c ${CFLAGS} node-list.c

node.o: node.c node.h
	${CC} -c ${CFLAGS} node.c

spjs-dispatch.o: spjs-dispatch.c node-list.h node.h
	${CC} -c ${CFLAGS} spjs-dispatch.c

spjs-hardware-specs.o: spjs-hardware-specs.c
	${CC} -c ${CFLAGS} spjs-hardware-specs.c

