    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set-opaque
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the node_list_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#ifndef _LPJS_NODE_H_
#include "node.h"
#endif

/* temp-node-list-accessors.c */
char *node_list_get_head_node(node_list_t *node_list_ptr);
char node_list_get_head_node_ae(node_list_t *node_list_ptr, size_t c);
unsigned node_list_get_compute_node_count(node_list_t *node_list_ptr);
node_t *node_list_get_compute_nodes_ae(node_list_t *node_list_ptr, size_t c);
