/***************************************************************************
 *  This file is automatically generated by gen-get-set.  Be sure to keep
 *  track of any manual changes.
 *
 *  These generated functions are not expected to be perfect.  Check and
 *  edit as needed before adding to your code.
 ***************************************************************************/

#include <string.h>
#include <ctype.h>
#include <stdbool.h>        // In case of bool
#include <stdint.h>         // In case of int64_t, etc
#include <xtend/string.h>   // strlcpy() on Linux
#include "node-private.h"


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      
 *
 *  Description:
 *      Accessor for hostname member in a node_t structure.
 *      Use this function to get hostname in a node_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member hostname.
 *
 *  Examples:
 *      node_t          node;
 *      char *          hostname;
 *
 *      hostname = node_get_hostname(&node);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-01  gen-get-set Auto-generated from node-private.h
 ***************************************************************************/

char *    node_get_hostname(node_t *node_ptr)

{
    return node_ptr->hostname;
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      
 *
 *  Description:
 *      Accessor for an array element of hostname member in a node_t
 *      structure. Use this function to get node_ptr->hostname[c]
 *      in a node_t object from non-member functions.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to get
 *      c               Subscript to the hostname array
 *
 *  Returns:
 *      Value of one element of structure member hostname.
 *
 *  Examples:
 *      node_t          node;
 *      size_t          c;
 *      char *          hostname_element;
 *
 *      hostname_element = node_get_hostname_ae(&node, c);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-01  gen-get-set Auto-generated from node-private.h
 ***************************************************************************/

char  node_get_hostname_ae(node_t *node_ptr, size_t c)

{
    return node_ptr->hostname[c];
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      
 *
 *  Description:
 *      Accessor for procs member in a node_t structure.
 *      Use this function to get procs in a node_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member procs.
 *
 *  Examples:
 *      node_t          node;
 *      unsigned        procs;
 *
 *      procs = node_get_procs(&node);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-01  gen-get-set Auto-generated from node-private.h
 ***************************************************************************/

unsigned    node_get_procs(node_t *node_ptr)

{
    return node_ptr->procs;
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      
 *
 *  Description:
 *      Accessor for procs_used member in a node_t structure.
 *      Use this function to get procs_used in a node_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member procs_used.
 *
 *  Examples:
 *      node_t          node;
 *      unsigned        procs_used;
 *
 *      procs_used = node_get_procs_used(&node);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-01  gen-get-set Auto-generated from node-private.h
 ***************************************************************************/

unsigned    node_get_procs_used(node_t *node_ptr)

{
    return node_ptr->procs_used;
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      
 *
 *  Description:
 *      Accessor for phys_MiB member in a node_t structure.
 *      Use this function to get phys_MiB in a node_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member phys_MiB.
 *
 *  Examples:
 *      node_t          node;
 *      unsigned long   phys_MiB;
 *
 *      phys_MiB = node_get_phys_MiB(&node);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-01  gen-get-set Auto-generated from node-private.h
 ***************************************************************************/

unsigned long    node_get_phys_MiB(node_t *node_ptr)

{
    return node_ptr->phys_MiB;
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      
 *
 *  Description:
 *      Accessor for phys_MiB_used member in a node_t structure.
 *      Use this function to get phys_MiB_used in a node_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member phys_MiB_used.
 *
 *  Examples:
 *      node_t          node;
 *      unsigned long   phys_MiB_used;
 *
 *      phys_MiB_used = node_get_phys_MiB_used(&node);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-01  gen-get-set Auto-generated from node-private.h
 ***************************************************************************/

unsigned long    node_get_phys_MiB_used(node_t *node_ptr)

{
    return node_ptr->phys_MiB_used;
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      
 *
 *  Description:
 *      Accessor for zfs member in a node_t structure.
 *      Use this function to get zfs in a node_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member zfs.
 *
 *  Examples:
 *      node_t          node;
 *      int             zfs;
 *
 *      zfs = node_get_zfs(&node);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-01  gen-get-set Auto-generated from node-private.h
 ***************************************************************************/

int    node_get_zfs(node_t *node_ptr)

{
    return node_ptr->zfs;
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      
 *
 *  Description:
 *      Accessor for os member in a node_t structure.
 *      Use this function to get os in a node_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member os.
 *
 *  Examples:
 *      node_t          node;
 *      char *          os;
 *
 *      os = node_get_os(&node);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-01  gen-get-set Auto-generated from node-private.h
 ***************************************************************************/

char *    node_get_os(node_t *node_ptr)

{
    return node_ptr->os;
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      
 *
 *  Description:
 *      Accessor for an array element of os member in a node_t
 *      structure. Use this function to get node_ptr->os[c]
 *      in a node_t object from non-member functions.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to get
 *      c               Subscript to the os array
 *
 *  Returns:
 *      Value of one element of structure member os.
 *
 *  Examples:
 *      node_t          node;
 *      size_t          c;
 *      char *          os_element;
 *
 *      os_element = node_get_os_ae(&node, c);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-01  gen-get-set Auto-generated from node-private.h
 ***************************************************************************/

char  node_get_os_ae(node_t *node_ptr, size_t c)

{
    return node_ptr->os[c];
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      
 *
 *  Description:
 *      Accessor for arch member in a node_t structure.
 *      Use this function to get arch in a node_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member arch.
 *
 *  Examples:
 *      node_t          node;
 *      char *          arch;
 *
 *      arch = node_get_arch(&node);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-01  gen-get-set Auto-generated from node-private.h
 ***************************************************************************/

char *    node_get_arch(node_t *node_ptr)

{
    return node_ptr->arch;
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      
 *
 *  Description:
 *      Accessor for an array element of arch member in a node_t
 *      structure. Use this function to get node_ptr->arch[c]
 *      in a node_t object from non-member functions.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to get
 *      c               Subscript to the arch array
 *
 *  Returns:
 *      Value of one element of structure member arch.
 *
 *  Examples:
 *      node_t          node;
 *      size_t          c;
 *      char *          arch_element;
 *
 *      arch_element = node_get_arch_ae(&node, c);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-01  gen-get-set Auto-generated from node-private.h
 ***************************************************************************/

char  node_get_arch_ae(node_t *node_ptr, size_t c)

{
    return node_ptr->arch[c];
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      
 *
 *  Description:
 *      Accessor for state member in a node_t structure.
 *      Use this function to get state in a node_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member state.
 *
 *  Examples:
 *      node_t          node;
 *      char *          state;
 *
 *      state = node_get_state(&node);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-01  gen-get-set Auto-generated from node-private.h
 ***************************************************************************/

char *    node_get_state(node_t *node_ptr)

{
    return node_ptr->state;
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      
 *
 *  Description:
 *      Accessor for an array element of state member in a node_t
 *      structure. Use this function to get node_ptr->state[c]
 *      in a node_t object from non-member functions.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to get
 *      c               Subscript to the state array
 *
 *  Returns:
 *      Value of one element of structure member state.
 *
 *  Examples:
 *      node_t          node;
 *      size_t          c;
 *      char *          state_element;
 *
 *      state_element = node_get_state_ae(&node, c);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-01  gen-get-set Auto-generated from node-private.h
 ***************************************************************************/

char  node_get_state_ae(node_t *node_ptr, size_t c)

{
    return node_ptr->state[c];
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      
 *
 *  Description:
 *      Accessor for msg_fd member in a node_t structure.
 *      Use this function to get msg_fd in a node_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member msg_fd.
 *
 *  Examples:
 *      node_t          node;
 *      int             msg_fd;
 *
 *      msg_fd = node_get_msg_fd(&node);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-01  gen-get-set Auto-generated from node-private.h
 ***************************************************************************/

int    node_get_msg_fd(node_t *node_ptr)

{
    return node_ptr->msg_fd;
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      
 *
 *  Description:
 *      Accessor for last_ping member in a node_t structure.
 *      Use this function to get last_ping in a node_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member last_ping.
 *
 *  Examples:
 *      node_t          node;
 *      time_t          last_ping;
 *
 *      last_ping = node_get_last_ping(&node);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-01  gen-get-set Auto-generated from node-private.h
 ***************************************************************************/

time_t    node_get_last_ping(node_t *node_ptr)

{
    return node_ptr->last_ping;
}
