/***************************************************************************
 *  This file is automatically generated by gen-get-set.  Be sure to keep
 *  track of any manual changes.
 *
 *  These generated functions are not expected to be perfect.  Check and
 *  edit as needed before adding to your code.
 ***************************************************************************/

#include <string.h>
#include <ctype.h>
#include <stdbool.h>        // In case of bool
#include <stdint.h>         // In case of int64_t, etc
#include <xtend/string.h>   // strlcpy() on Linux
#include "node-list-private.h"


/***************************************************************************
 *  Library:
 *      #include <node-list.h>
 *      
 *
 *  Description:
 *      Accessor for head_node member in a node_list_t structure.
 *      Use this function to get head_node in a node_list_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      node_list_ptr   Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member head_node.
 *
 *  Examples:
 *      node_list_t     node_list;
 *      char *          head_node;
 *
 *      head_node = node_list_get_head_node(&node_list);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-23  gen-get-set Auto-generated from node-list-private.h
 ***************************************************************************/

char *    node_list_get_head_node(node_list_t *node_list_ptr)

{
    return node_list_ptr->head_node;
}


/***************************************************************************
 *  Library:
 *      #include <node-list.h>
 *      
 *
 *  Description:
 *      Accessor for an array element of head_node member in a node_list_t
 *      structure. Use this function to get node_list_ptr->head_node[c]
 *      in a node_list_t object from non-member functions.
 *
 *  Arguments:
 *      node_list_ptr   Pointer to the structure to get
 *      c               Subscript to the head_node array
 *
 *  Returns:
 *      Value of one element of structure member head_node.
 *
 *  Examples:
 *      node_list_t     node_list;
 *      size_t          c;
 *      char *          head_node_element;
 *
 *      head_node_element = node_list_get_head_node_ae(&node_list, c);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-23  gen-get-set Auto-generated from node-list-private.h
 ***************************************************************************/

char  node_list_get_head_node_ae(node_list_t *node_list_ptr, size_t c)

{
    return node_list_ptr->head_node[c];
}


/***************************************************************************
 *  Library:
 *      #include <node-list.h>
 *      
 *
 *  Description:
 *      Accessor for compute_node_count member in a node_list_t structure.
 *      Use this function to get compute_node_count in a node_list_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      node_list_ptr   Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member compute_node_count.
 *
 *  Examples:
 *      node_list_t     node_list;
 *      unsigned        compute_node_count;
 *
 *      compute_node_count = node_list_get_compute_node_count(&node_list);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-23  gen-get-set Auto-generated from node-list-private.h
 ***************************************************************************/

unsigned    node_list_get_compute_node_count(node_list_t *node_list_ptr)

{
    return node_list_ptr->compute_node_count;
}


/***************************************************************************
 *  Library:
 *      #include <node-list.h>
 *      
 *
 *  Description:
 *      Accessor for an array element of compute_nodes member in a node_list_t
 *      structure. Use this function to get node_list_ptr->compute_nodes[c]
 *      in a node_list_t object from non-member functions.
 *
 *  Arguments:
 *      node_list_ptr   Pointer to the structure to get
 *      c               Subscript to the compute_nodes array
 *
 *  Returns:
 *      Value of one element of structure member compute_nodes.
 *
 *  Examples:
 *      node_list_t     node_list;
 *      size_t          c;
 *      node_t *        compute_nodes_element;
 *
 *      compute_nodes_element = node_list_get_compute_nodes_ae(&node_list, c);
 *
 *  History: 
 *  Date        Name        Modification
 *  2024-02-23  gen-get-set Auto-generated from node-list-private.h
 ***************************************************************************/

node_t  *node_list_get_compute_nodes_ae(node_list_t *node_list_ptr, size_t c)

{
    return node_list_ptr->compute_nodes[c];
}
