/***************************************************************************
 *  This file is automatically generated by gen-get-set.  Be sure to keep
 *  track of any manual changes.
 *
 *  These generated functions are not expected to be perfect.  Check and
 *  edit as needed before adding to your code.
 ***************************************************************************/

#include <string.h>
#include <ctype.h>

#include <xtend/string.h>   // strlcpy() on Linux

#include "node-list.h"


/***************************************************************************
 *  Library:
 *      #include <node-list.h>
 *      
 *
 *  Description:
 *      Mutator for head_node member in a node_list_t structure.
 *      Use this function to set head_node in a node_list_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      head_node is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_head_node is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      node_list_ptr   Pointer to the structure to set
 *      new_head_node   The new value for head_node
 *
 *  Returns:
 *      NODE_LIST_DATA_OK if the new value is acceptable and assigned
 *      NODE_LIST_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      node_list_t     node_list;
 *      char *          new_head_node;
 *
 *      if ( node_list_set_head_node(&node_list, new_head_node) == NODE_LIST_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-27  gen-get-set Auto-generated from node-list.h
 ***************************************************************************/

int     node_list_set_head_node(node_list_t *node_list_ptr, char * new_head_node)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( new_head_node == NULL )
	return NODE_LIST_DATA_OUT_OF_RANGE;
    else
    {
	node_list_ptr->head_node = new_head_node;
	return NODE_LIST_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <node-list.h>
 *      
 *
 *  Description:
 *      Mutator for an array element of head_node member in a node_list_t
 *      structure. Use this function to set an element of the array
 *      head_node in a node_list_t variable from non-member functions.
 *
 *      Note that there is an equivalent macro NODE_LIST_SET_HEAD_NODE_AE(), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_head_node_element is guaranteed by other means.
 *
 *  Arguments:
 *      node_list_ptr   Pointer to the structure to set
 *      c               Subscript to the head_node array
 *      new_head_node_element The new value for head_node[c]
 *
 *  Returns:
 *      NODE_LIST_DATA_OK if the new value is acceptable and assigned
 *      NODE_LIST_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      node_list_t     node_list;
 *      size_t          c;
 *      char *          new_head_node_element;
 *
 *      if ( node_list_set_head_node(&node_list, c, new_head_node_element) == NODE_LIST_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      NODE_LIST_SET_HEAD_NODE_AE(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-27  gen-get-set Auto-generated from node-list.h
 ***************************************************************************/

int     node_list_set_head_node_ae(node_list_t *node_list_ptr, size_t c, char  new_head_node_element)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return NODE_LIST_DATA_OUT_OF_RANGE;
    else
    {
	node_list_ptr->head_node[c] = new_head_node_element;
	return NODE_LIST_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <node-list.h>
 *      
 *
 *  Description:
 *      Mutator for head_node member in a node_list_t structure.
 *      Use this function to set head_node in a node_list_t variable
 *      from non-member functions.  This function copies the array pointed to
 *      by new_head_node to ->head_node.
 *
 *      Note that there is an equivalent macro NODE_LIST_SET_HEAD_NODE(), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_head_node is guaranteed by other means.
 *
 *  Arguments:
 *      node_list_ptr   Pointer to the structure to set
 *      new_head_node   The new value for head_node
 *      array_size      Size of the head_node array.
 *
 *  Returns:
 *      NODE_LIST_DATA_OK if the new value is acceptable and assigned
 *      NODE_LIST_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      node_list_t     node_list;
 *      char *          new_head_node;
 *      size_t          array_size;
 *
 *      if ( node_list_set_head_node(&node_list, new_head_node, array_size) == NODE_LIST_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      NODE_LIST_SET_HEAD_NODE(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-27  gen-get-set Auto-generated from node-list.h
 ***************************************************************************/

int     node_list_set_head_node_cpy(node_list_t *node_list_ptr, char * new_head_node, size_t array_size)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( new_head_node == NULL )
	return NODE_LIST_DATA_OUT_OF_RANGE;
    else
    {
	// FIXME: Assuming char array is a null-terminated string
	strlcpy(node_list_ptr->head_node, new_head_node, array_size);
	return NODE_LIST_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <node-list.h>
 *      
 *
 *  Description:
 *      Mutator for count member in a node_list_t structure.
 *      Use this function to set count in a node_list_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      count is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_count is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      node_list_ptr   Pointer to the structure to set
 *      new_count       The new value for count
 *
 *  Returns:
 *      NODE_LIST_DATA_OK if the new value is acceptable and assigned
 *      NODE_LIST_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      node_list_t     node_list;
 *      unsigned        new_count;
 *
 *      if ( node_list_set_count(&node_list, new_count) == NODE_LIST_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-27  gen-get-set Auto-generated from node-list.h
 ***************************************************************************/

int     node_list_set_count(node_list_t *node_list_ptr, unsigned new_count)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return NODE_LIST_DATA_OUT_OF_RANGE;
    else
    {
	node_list_ptr->count = new_count;
	return NODE_LIST_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <node-list.h>
 *      
 *
 *  Description:
 *      Mutator for an array element of compute_nodes member in a node_list_t
 *      structure. Use this function to set an element of the array
 *      compute_nodes in a node_list_t variable from non-member functions.
 *
 *      Note that there is an equivalent macro NODE_LIST_SET_COMPUTE_NODES_AE(), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_compute_nodes_element is guaranteed by other means.
 *
 *  Arguments:
 *      node_list_ptr   Pointer to the structure to set
 *      c               Subscript to the compute_nodes array
 *      new_compute_nodes_element The new value for compute_nodes[c]
 *
 *  Returns:
 *      NODE_LIST_DATA_OK if the new value is acceptable and assigned
 *      NODE_LIST_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      node_list_t     node_list;
 *      size_t          c;
 *      node_t          new_compute_nodes_element;
 *
 *      if ( node_list_set_compute_nodes(&node_list, c, new_compute_nodes_element) == NODE_LIST_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      NODE_LIST_SET_COMPUTE_NODES_AE(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-27  gen-get-set Auto-generated from node-list.h
 ***************************************************************************/

int     node_list_set_compute_nodes_ae(node_list_t *node_list_ptr, size_t c, node_t new_compute_nodes_element)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return NODE_LIST_DATA_OUT_OF_RANGE;
    else
    {
	node_list_ptr->compute_nodes[c] = new_compute_nodes_element;
	return NODE_LIST_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <node-list.h>
 *      
 *
 *  Description:
 *      Mutator for compute_nodes member in a node_list_t structure.
 *      Use this function to set compute_nodes in a node_list_t variable
 *      from non-member functions.  This function copies the array pointed to
 *      by new_compute_nodes to ->compute_nodes.
 *
 *      Note that there is an equivalent macro NODE_LIST_SET_COMPUTE_NODES(), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_compute_nodes is guaranteed by other means.
 *
 *  Arguments:
 *      node_list_ptr   Pointer to the structure to set
 *      new_compute_nodes The new value for compute_nodes
 *      array_size      Size of the compute_nodes array.
 *
 *  Returns:
 *      NODE_LIST_DATA_OK if the new value is acceptable and assigned
 *      NODE_LIST_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      node_list_t     node_list;
 *      node_t          new_compute_nodes;
 *      size_t          array_size;
 *
 *      if ( node_list_set_compute_nodes(&node_list, new_compute_nodes, array_size) == NODE_LIST_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      NODE_LIST_SET_COMPUTE_NODES(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-27  gen-get-set Auto-generated from node-list.h
 ***************************************************************************/

int     node_list_set_compute_nodes_cpy(node_list_t *node_list_ptr, node_t new_compute_nodes[], size_t array_size)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( new_compute_nodes == NULL )
	return NODE_LIST_DATA_OUT_OF_RANGE;
    else
    {
	{
	    size_t  c;
	    
	    // FIXME: Assuming all elements should be copied
	    for (c = 0; c < array_size; ++c)
		node_list_ptr->compute_nodes[c] = new_compute_nodes[c];
	}
	return NODE_LIST_DATA_OK;
    }
}
