
/*
 *  Generated by /usr/local/bin/auto-gen-get-set-opaque
 *
 *  Mutator functions for setting with no sanity checking.  Use these to
 *  set structure members from functions outside the node_list_t
 *  class.  These macros perform no data validation.  Hence, they achieve
 *  maximum performance where data are guaranteed correct by other means.
 *  Use the mutator functions (same name as the macro, but lower case)
 *  for more robust code with a small performance penalty.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

/* temp-node-list-mutators.c */
int node_list_set_head_node(node_list_t *node_list_ptr, char *new_head_node);
int node_list_set_head_node_ae(node_list_t *node_list_ptr, size_t c, char new_head_node_element);
int node_list_set_head_node_cpy(node_list_t *node_list_ptr, char *new_head_node, size_t array_size);
int node_list_set_compute_node_count(node_list_t *node_list_ptr, unsigned new_compute_node_count);
int node_list_set_compute_nodes_ae(node_list_t *node_list_ptr, size_t c, node_t *new_compute_nodes_element);
int node_list_set_compute_nodes_cpy(node_list_t *node_list_ptr, node_t *new_compute_nodes[], size_t array_size);
