    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set-transparent
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the node_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define NODE_HOSTNAME(ptr)              ((ptr)->hostname)
#define NODE_HOSTNAME_AE(ptr,c)         ((ptr)->hostname[c])
#define NODE_CORES(ptr)                 ((ptr)->cores)
#define NODE_CORES_USED(ptr)            ((ptr)->cores_used)
#define NODE_PHYS_MEM(ptr)              ((ptr)->phys_mem)
#define NODE_PHYS_MEM_USED(ptr)         ((ptr)->phys_mem_used)
#define NODE_ZFS(ptr)                   ((ptr)->zfs)
#define NODE_OS(ptr)                    ((ptr)->os)
#define NODE_OS_AE(ptr,c)               ((ptr)->os[c])
#define NODE_ARCH(ptr)                  ((ptr)->arch)
#define NODE_ARCH_AE(ptr,c)             ((ptr)->arch[c])
#define NODE_STATE(ptr)                 ((ptr)->state)
#define NODE_STATE_AE(ptr,c)            ((ptr)->state[c])
#define NODE_MSG_FD(ptr)                ((ptr)->msg_fd)
#define NODE_LAST_PING(ptr)             ((ptr)->last_ping)
