/***************************************************************************
 *  This file is automatically generated by gen-get-set.  Be sure to keep
 *  track of any manual changes.
 *
 *  These generated functions are not expected to be perfect.  Check and
 *  edit as needed before adding to your code.
 ***************************************************************************/

#include <string.h>
#include <ctype.h>
#include <xtend/string.h>   // strlcpy() on Linux
#include "node.h"


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for hostname member in a node_t structure.
 *      Use this function to set hostname in a node_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      hostname is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_hostname is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *      new_hostname    The new value for hostname
 *
 *  Returns:
 *      NODE_DATA_OK if the new value is acceptable and assigned
 *      NODE_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      node_t          node;
 *      char *          new_hostname;
 *
 *      if ( node_set_hostname(&node, new_hostname) == NODE_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-23  gen-get-set Auto-generated from node.h
 ***************************************************************************/

int     node_set_hostname(node_t *node_ptr, char * new_hostname)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( new_hostname == NULL )
	return NODE_DATA_OUT_OF_RANGE;
    else
    {
	node_ptr->hostname = new_hostname;
	return NODE_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for an array element of hostname member in a node_t
 *      structure. Use this function to set an element of the array
 *      hostname in a node_t variable from non-member functions.
 *
 *      Note that there is an equivalent macro NODE_SET_HOSTNAME_AE(), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_hostname_element is guaranteed by other means.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *      c               Subscript to the hostname array
 *      new_hostname_element The new value for hostname[c]
 *
 *  Returns:
 *      NODE_DATA_OK if the new value is acceptable and assigned
 *      NODE_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      node_t          node;
 *      size_t          c;
 *      char *          new_hostname_element;
 *
 *      if ( node_set_hostname(&node, c, new_hostname_element) == NODE_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      NODE_SET_HOSTNAME_AE(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-23  gen-get-set Auto-generated from node.h
 ***************************************************************************/

int     node_set_hostname_ae(node_t *node_ptr, size_t c, char  new_hostname_element)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return NODE_DATA_OUT_OF_RANGE;
    else
    {
	node_ptr->hostname[c] = new_hostname_element;
	return NODE_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for hostname member in a node_t structure.
 *      Use this function to set hostname in a node_t variable
 *      from non-member functions.  This function copies the array pointed to
 *      by new_hostname to ->hostname.
 *
 *      Note that there is an equivalent macro NODE_SET_HOSTNAME(), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_hostname is guaranteed by other means.
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *      new_hostname    The new value for hostname
 *      array_size      Size of the hostname array.
 *
 *  Returns:
 *      NODE_DATA_OK if the new value is acceptable and assigned
 *      NODE_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      node_t          node;
 *      char *          new_hostname;
 *      size_t          array_size;
 *
 *      if ( node_set_hostname(&node, new_hostname, array_size) == NODE_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      NODE_SET_HOSTNAME(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-23  gen-get-set Auto-generated from node.h
 ***************************************************************************/

int     node_set_hostname_cpy(node_t *node_ptr, char * new_hostname, size_t array_size)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( new_hostname == NULL )
	return NODE_DATA_OUT_OF_RANGE;
    else
    {
	// FIXME: Assuming char array is a null-terminated string
	strlcpy(node_ptr->hostname, new_hostname, array_size);
	return NODE_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for cores member in a node_t structure.
 *      Use this function to set cores in a node_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      cores is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_cores is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *      new_cores       The new value for cores
 *
 *  Returns:
 *      NODE_DATA_OK if the new value is acceptable and assigned
 *      NODE_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      node_t          node;
 *      unsigned        new_cores;
 *
 *      if ( node_set_cores(&node, new_cores) == NODE_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-23  gen-get-set Auto-generated from node.h
 ***************************************************************************/

int     node_set_cores(node_t *node_ptr, unsigned new_cores)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return NODE_DATA_OUT_OF_RANGE;
    else
    {
	node_ptr->cores = new_cores;
	return NODE_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for cores_used member in a node_t structure.
 *      Use this function to set cores_used in a node_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      cores_used is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_cores_used is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *      new_cores_used  The new value for cores_used
 *
 *  Returns:
 *      NODE_DATA_OK if the new value is acceptable and assigned
 *      NODE_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      node_t          node;
 *      unsigned        new_cores_used;
 *
 *      if ( node_set_cores_used(&node, new_cores_used) == NODE_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-23  gen-get-set Auto-generated from node.h
 ***************************************************************************/

int     node_set_cores_used(node_t *node_ptr, unsigned new_cores_used)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return NODE_DATA_OUT_OF_RANGE;
    else
    {
	node_ptr->cores_used = new_cores_used;
	return NODE_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for mem member in a node_t structure.
 *      Use this function to set mem in a node_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      mem is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_mem is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *      new_mem         The new value for mem
 *
 *  Returns:
 *      NODE_DATA_OK if the new value is acceptable and assigned
 *      NODE_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      node_t          node;
 *      unsigned long   new_mem;
 *
 *      if ( node_set_mem(&node, new_mem) == NODE_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-23  gen-get-set Auto-generated from node.h
 ***************************************************************************/

int     node_set_mem(node_t *node_ptr, unsigned long new_mem)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return NODE_DATA_OUT_OF_RANGE;
    else
    {
	node_ptr->mem = new_mem;
	return NODE_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <node.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for mem_used member in a node_t structure.
 *      Use this function to set mem_used in a node_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      mem_used is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_mem_used is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      node_ptr        Pointer to the structure to set
 *      new_mem_used    The new value for mem_used
 *
 *  Returns:
 *      NODE_DATA_OK if the new value is acceptable and assigned
 *      NODE_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      node_t          node;
 *      unsigned long   new_mem_used;
 *
 *      if ( node_set_mem_used(&node, new_mem_used) == NODE_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-23  gen-get-set Auto-generated from node.h
 ***************************************************************************/

int     node_set_mem_used(node_t *node_ptr, unsigned long new_mem_used)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return NODE_DATA_OUT_OF_RANGE;
    else
    {
	node_ptr->mem_used = new_mem_used;
	return NODE_DATA_OK;
    }
}
