#!/bin/sh

##########################################################################
#   Title:
#       lpjs-adhoc
#
#   Synopsis:
#       lpjs ad-hoc
#
#   Description:
#       This script provides a terminal-base menu system for starting
#       up an ad-hoc cluster or grid, i.e. one where the dispatch and
#       compute daemons are started and stopped manually, rather than
#       using system services.
#       
#   Arguments:
#       None
#       
#   Returns:
#       0 on success, non-zero error codes otherwise
#
#   See also:
#       lpjs-admin(1), lpjs-menu(1)
#       
#   History:
#   Date        Name        Modification
#   2021-10-06  J Bacon     Begin
##########################################################################

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Function description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2024-03-22  Jason Bacon Begin
##########################################################################

start_daemon()
{
    if [ $# != 1 ]; then
	printf "Usage: start_daemon command\n"
	return 1
    fi
    daemon=$1
    
    resp=''
    while [ 0"$resp" != 01 ] && [ 0"$resp" != 02 ]; do
	cat << EOM

1.. Foreground (log messages on-screen and do not return to menu)
2.. Background (log messages to file and return to menu)

EOM
	printf "Selection? "
	read resp
    done
    if [ $resp = 1 ]; then
	printf "Type Ctrl+c to terminate $daemon.\n"
	pause
	if [ $daemon = munged ]; then
	    $daemon --foreground
	else
	    $daemon
	fi
	pause
    else
	printf "Logged messages can be viewed using \"lpjs log\"\n"
	printf "or the \"View log(s)\" menu option.\n"
	pause
	if [ $daemon = munged ]; then
	    $daemon
	else
	    $daemon --daemonize
	fi
	echo $?
	pgrep -lf $daemon
	pause
    fi
}

##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

: ${EDITOR:=vi}

while true
do
    clear
    /usr/local/libexec/lpjs/banner
    cat << EOM

1.. Manually start munged (required by both dispatchd and compd)
2.. Manually start dispatchd (temporarily make this a head node)
3.. Manually start compd (temporarily make this a compute node)
4.. Stop background munged
5.. Stop background dispatchd
6.. Stop background compd
7.. View log(s)
Q.. Quit

EOM

    read -p 'Selection? ' resp
    case 0$resp in
    01)
	start_daemon munged
	;;
    
    02)
	start_daemon lpjs_dispatchd
	;;
    
    03)
	start_daemon lpjs_compd
	;;

    04)
	printf "Before pkill:\n"
	pgrep -lf munged
	pkill -f munged
	printf "After pkill:\n"
	sleep 1
	pgrep -lf munged
	pause
	;;
    
    05)
	printf "Before pkill:\n"
	pgrep -lf lpjs_dispatchd
	pkill -f lpjs_dispatchd
	sleep 1
	printf "After pkill:\n"
	pgrep -lf lpjs_dispatchd
	pause
	;;
    
    06)
	printf "Before pkill:\n"
	pgrep -lf lpjs_compd
	pkill -f lpjs_compd
	sleep 1
	printf "After pkill:\n"
	pgrep -lf lpjs_compd
	pause
	;;
    
    07)
	lpjs log
	pause
	;;

    0Q|0q)
	exit 0
	;;

    *)
	printf "Invalid option: $resp\n"
    esac
done
