#!/bin/sh

##########################################################################
#   Script description:
#       Menu for basic LPJS setup
#       
#   History:
#   Date        Name        Modification
#   2021-10-06  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

: ${EDITOR:=vi}

while true
do
    clear
    lpjs-banner
    cat << EOM

1.. Node status
2.. Job status
3.. Generate or edit job script
4.. Submit a job
Q.. Quit

EOM

    read -p 'Selection? ' resp
    case 0$resp in
    01)
	printf "Running lpjs nodes...\n\n"
	lpjs nodes
	pause
	;;
    
    02)
	printf "Running lpjs jobs...\n\n"
	lpjs jobs
	pause
	;;

    03)
	read -p 'Script name? (".lpjs" will be added) ' script
	if [ ${script##*.} != lpjs ]; then
	    script=$script.lpjs
	fi
	if [ ! -e $script ]; then
	    printf "Running lpjs create-script $script...\n"
	    pause
	    lpjs create-script $script
	else
	    $EDITOR $script
	fi
	;;
    
    04)
	ls *.lpjs
	read -p 'Script name? (".lpjs" will be added) ' script
	if [ ${script##*.} != lpjs ]; then
	    script=$script.lpjs
	fi
	read -p 'Submit? y/[n] ' submit
	if [ 0"$submit" = 0y ]; then
	    printf "Running lpjs submit $script...\n\n"
	    lpjs submit $script
	fi
	pause
	;;

    0Q|0q)
	exit 0
	;;

    *)
	printf "Invalid option: $resp\n"
    esac
done
