#!/bin/sh -e

##########################################################################
#   Synopsis:
#       lpjs run-time log-dir
#       
#   Arguments:
#       log-dir     The main log directory for the job submission
#       
#   Description:
#       .B lpjs run-time
#       Shows the begin and end times for all completed jobs logged
#       under log-dir.
#       
#   Examples:
#       lpjs run-time Logs/17-bowtie2-align/
#       ===
#       Logs/17-bowtie2-align/Job-1836/chaperone-1836.stderr
#       01-21 15:06:23 lpjs_job_start_notice_loop(): Start notice successful.
#       01-21 17:22:12 main(): Info: Job process exited with status 0.
#       ===
#       Logs/17-bowtie2-align/Job-1837/chaperone-1837.stderr
#       01-21 15:06:23 lpjs_job_start_notice_loop(): Start notice successful.
#       01-21 17:57:14 main(): Info: Job process exited with status 0.
#       ===
#       Logs/17-bowtie2-align/Job-1838/chaperone-1838.stderr
#       01-21 15:06:23 lpjs_job_start_notice_loop(): Start notice successful.
#       01-21 16:59:46 main(): Info: Job process exited with status 0.
#
#   See also:
#       lpjs-peak-mem(1)
#       
#   History:
#   Date        Name        Modification
#   2025-01-21  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 log-dir\n"
    exit 64     # sysexits(3) EX_USAGE
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
log_dir="${1%/}"    # Trim trailing / if present
for log in $log_dir/Job-*/chaperone*.stderr; do
    if fgrep -q 'Job process exited' $log; then
	printf "===\n$log\n"
	fgrep 'Start notice success' $log
	fgrep 'Job process exited' $log
    fi
done
