#!/bin/sh -e

##########################################################################
#   Function description:
#       Enable compd on this node (make this a compute node)
#       
#   History:
#   Date        Name        Modification
#   2023-05-28  Jason Bacon Begin
##########################################################################

if [ ! -e $CONF_FILE ] || ! grep -q '^head' $CONF_FILE; then
    printf "Host name of head node? "
    read head_node
    printf "head    $head_node\n" >> $CONF_FILE
else
    head_node=$(awk '$1 == "head" { print $2 }' $CONF_FILE)
fi

printf "Add 'compute $(hostname)' to $CONF_FILE on $head_node.\n"
pause
/usr/local/libexec/lpjs/munge-enable
if [ $(uname) = Darwin ]; then
    plist=$(auto-localbase)/share/lpjs/Launchd/org.pkgsrc.lpjs_compd.plist
    if [ -e $plist ]; then
	auto-enable-service -s $plist org.pkgsrc.lpjs_compd lpjs-admin
    fi
elif [ $(uname) = Linux ]; then
    script=$(auto-localbase)/share/lpjs/Systemd/lpjs_compd.service
    if [ -e $script ]; then
	auto-enable-service -s $script lpjs_compd lpjs-admin
    fi
elif [ $(uname) = SunOS ]; then
    # FIXME: Copying to /etc/init.d doesn't cause startup at boot
    cp $(auto-localbase)/etc/init.d/munge /etc/init.d
/et /etc/init.d/munge restart
    printf "lpjs daemons not yet implemented for SunOS.\n"
else
    auto-enable-service lpjs_compd $0
fi

