#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

##########################################################################
#   Title:
#       lpjs-compd-enable
#
#   Section:
#       8
#
#   Synopsis:
#       lpjs compd-enable
#       
#   Description:
#       lpjs compd-enable is a convenience script for enabling and
#       starting the LPJS compute daemon, lpjs_compd(8).  It simply
#       runs auto-enable-service(8), part of the auto-admin package,
#       with the appropriate arguments.
#       
#   Arguments:
#       None
#       
#   Returns:
#       0 on success, non-zero error codes otherwise
#
#   See also:
#       lpjs-admin(8), lpjs-compd-disable(8), lpjs-dispatchd-disable(8),
#       lpjs-dispatchd-enable(8), lpjs-restart(8), lpjs-start(8),
#       lpjs-stop(8)
#       
#   History:
#   Date        Name        Modification
#   2023-05-28  Jason Bacon Begin
##########################################################################

CONF_FILE=/usr/local/etc/lpjs/config

if [ ! -e $CONF_FILE ] || ! grep -q '^head' $CONF_FILE; then
    printf "Host name of head node? "
    read head_node
    printf "head    $head_node\n" >> $CONF_FILE
else
    head_node=$(awk '$1 == "head" { print $2 }' $CONF_FILE)
fi

if [ 0$1 != 0--batch ]; then
    cat << EOM

Add 'compute $(hostname)' to $CONF_FILE on
$head_node.

Then run "lpjs restart" on $head_node.

EOM
    pause
    /usr/local/libexec/lpjs/SMI/munge-enable
fi

if [ $(uname) = Darwin ]; then
    plist=/usr/local/share/lpjs/Launchd/org.pkgsrc.lpjs_compd.plist
    if [ -e $plist ]; then
	auto-enable-service -s $plist org.pkgsrc.lpjs_compd lpjs-admin
    fi
elif [ $(uname) = Linux ]; then
    script=/usr/local/share/lpjs/Systemd/lpjs_compd.service
    if [ -e $script ]; then
	auto-enable-service -s $script lpjs_compd lpjs-admin
    fi
elif [ $(uname) = SunOS ]; then
    # FIXME: Copying to /etc/init.d doesn't cause startup at boot
    cp /usr/local/etc/init.d/munge /etc/init.d
    /etc/init.d/munge restart
    printf "lpjs daemons not yet implemented for SunOS.\n"
else
    if auto-service-enabled lpjs_compd; then
	lpjs restart
    else
	auto-enable-service lpjs_compd $0
    fi
fi
