#!/bin/sh -ex

##########################################################################
#   Title:
#       lpjs-compd-disable
#
#   Section:
#       8
#
#   Synopsis:
#       lpjs compd-disable
#       
#   Description:
#       lpjs compd-disable is a convenience script for stopping and
#       disabling the LPJS compute daemon, lpjs_compd(8).  It simply
#       runs auto-disable-service(8), part of the auto-admin package,
#       with the appropriate arguments.
#       
#   Arguments:
#       None
#       
#   Returns:
#       0 on success, non-zero error codes otherwise
#
#   See also:
#       lpjs-admin(8), lpjs-compd-enable(8), lpjs-dispatchd-disable(8),
#       lpjs-dispatchd-enable(8), lpjs-restart(8), lpjs-start(8),
#       lpjs-stop(8)
#       
#   History:
#   Date        Name        Modification
#   2023-05-28  Jason Bacon Begin
##########################################################################

# Don't disable munged.  Let that be done separately.
auto-disable-service lpjs_compd
rm -i /usr/local/var/log/lpjs/compd
