#!/bin/sh -ex

##########################################################################
#   Title:
#       lpjs-dispatchd-disable
#
#   Section:
#       8
#
#   Synopsis:
#       lpjs dispatchd-disable
#       
#   Description:
#       lpjs dispatchd-disable is a convenience script for stopping and
#       disabling the LPJS dispatch daemon, lpjs_dispatchd(8).  It simply
#       runs auto-enable-service(8), part of the auto-admin package,
#       with the appropriate arguments.
#       
#   Arguments:
#       None
#       
#   Returns:
#       0 on success, non-zero error codes otherwise
#
#   See also:
#       lpjs-admin(8), lpjs-compd-enable(8), lpjs-compd-disable(8),
#       lpjs-dispatchd-enable(8), lpjs-restart(8), lpjs-start(8),
#       lpjs-stop(8)
#       
#   History:
#   Date        Name        Modification
#   2023-05-28  Jason Bacon Begin
##########################################################################

# Don't disable munge, let that be done separately
auto-disable-service lpjs_dispatchd
rm -i /usr/local/var/log/lpjs/dispatchd
