#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Title:
#       lpjs-dispatchd-enable
#
#   Section:
#       8
#
#   Synopsis:
#       lpjs dispatchd-enable
#       
#   Description:
#       lpjs dispatchd-enable is a convenience script for enabling and
#       starting the LPJS compute daemon, lpjs_dispatchd(8).  It simply
#       runs auto-enable-service(8), part of the auto-admin package,
#       with the appropriate arguments.
#       
#   Arguments:
#       None
#       
#   Returns:
#       0 on success, non-zero error codes otherwise
#
#   See also:
#       lpjs-admin(8), lpjs-compd-disable(8), lpjs-dispatchd-disable(8),
#       lpjs-compd-enable(8), lpjs-restart(8), lpjs-start(8),
#       lpjs-stop(8)
#       
#   History:
#   Date        Name        Modification
#   2023-05-28  Jason Bacon Begin
##########################################################################

CONF_FILE=/usr/local/etc/lpjs/config

if grep -q '^head' $CONF_FILE; then
    head_node=$(awk '$1 == "head" { print $2 }' $CONF_FILE)
    if [ 0$head_node != 0$(hostname) ]; then
	printf "This node currently lists $head_node as the head node.\n"
	printf "$head_node will be replaced by $(hostname).\n"
	printf "Proceed? y/[n] "
	read proceed
	if [ 0"$proceed" = 0y ]; then
	    head_node=$(hostname)
	    printf "head    $head_node\n" >> $CONF_FILE.temp
	    grep -v '^head' $CONF_FILE >> $CONF_FILE.temp || true
	    mv -f $CONF_FILE.temp $CONF_FILE
	    chmod 644 $CONF_FILE
	    chown lpjs:lpjs $CONF_FILE
	fi
    fi
fi
/usr/local/libexec/lpjs/SMI/munge-enable
if [ $(uname) = Darwin ]; then
    plist=/usr/local/share/lpjs/Launchd/org.pkgsrc.lpjs_dispatchd.plist
    if [ -e $plist ]; then
	auto-enable-service -s $plist org.pkgsrc.lpjs_dispatchd lpjs-admin
    fi
elif [ $(uname) = Linux ]; then
    # FIXME: systemd-specific
    script=/usr/local/share/lpjs/Systemd/lpjs_dispatchd.service
    if [ -e $script ]; then
	auto-enable-service -s $script lpjs_dispatchd lpjs-admin
    fi
elif [ $(uname) = SunOS ]; then
    # FIXME: Copying to /etc/init.d doesn't cause startup at boot
    cp /usr/local/etc/init.d/munge /etc/init.d
/et /etc/init.d/munge restart
    printf "lpjs daemons not yet implemented for SunOS.\n"
else
    auto-enable-service lpjs_dispatchd $0
fi
