#!/bin/sh -ex

##########################################################################
#   Description:
#       Disable dispatchd on this node
#       
#   History:
#   Date        Name        Modification
#   2023-05-28  Jason Bacon Begin
##########################################################################

# Don't disable munge, let that be done separately
auto-disable-service lpjs_dispatchd
