#!/bin/sh -e

##########################################################################
#   Title:
#       lpjs-history
#
#   Section:
#       8
#
#   Synopsis:
#       lpjs history
#       
#   Description:
#       lpjs history is a convenience script for displaying the LPJS job
#       history.  The location of the history file is dependent on the
#       operating system and package manager used to install LPJS.  lpjs history
#       eliminates the need to know this location or to type lengthy
#       pathnames.
#       
#   Arguments:
#       None
#       
#   Returns:
#       0 upon success, non-zero error codes otherwise
#
#   See also:
#       lpjs-admin(8)
#       
#   History:
#   Date        Name        Modification
#   2024-02-20  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 [--long]\n"
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Main
##########################################################################

case $# in
0)
    ;;

1)
    if [ 0"$1" != 0--long ]; then
	usage
    fi
    ;;
*)
    usage
esac

log_dir=/usr/local/var/log/lpjs
if [ ! -e $log_dir ]; then
    exit 0
fi

# FIXME: Add a --long flag to output in human-readable format
if [ 0"$1" = 0--long ]; then
    awk '{ printf("job-id=%s exit-status=%s peak-pmem=%sKiB pmem-per-processor=%sKiB compute-node=%s user=%s script=%s\n", $1, $2, $3, $4, $5, $6, $7); }' $log_dir/job-history
else
    cat $log_dir/job-history
fi
