#!/bin/sh -e

##########################################################################
#   Title:
#       lpjs-log
#
#   Section:
#       8
#
#   Synopsis:
#       lpjs log
#       
#   Description:
#       lpjs log is a convenience script for displaying all LPJS log
#       files.  The location of the logs is dependent on the operating
#       system and package manager used to install LPJS.  lpjs log
#       eliminates the need to know this location or to type lengthy
#       pathnames.
#       
#   Arguments:
#       None
#       
#   Returns:
#       0 upon success, non-zero error codes otherwise
#
#   See also:
#       lpjs-admin(8)
#       
#   History:
#   Date        Name        Modification
#   2024-02-20  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi
log_dir=/usr/local/var/log/lpjs
if [ ! -e $log_dir ]; then
    exit 0
fi

for file in $log_dir/*; do
    # job-history is viewed by the separate lpjs history command
    if [ "$file" != $log_dir/job-history ]; then
	cat $file
	printf "===\nEnd of $file.\n"
	if [ $(ls $log_dir | wc -w) -gt 1 ]; then
	    pause
	fi
    fi
done
