#!/bin/sh -e

##########################################################################
#   Synopsis:
#       
#   Description:
#       
#   Arguments:
#       
#   Returns:
#
#   Examples:
#
#   Files:
#
#   Environment:
#
#   See also:
#       
#   History:
#   Date        Name        Modification
#   2024-02-20  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi
log_dir=/usr/local/var/log/lpjs
if [ ! -e $log_dir ]; then
    exit 0
fi

for file in $log_dir/*; do
    cat $file
    printf "===\nEnd of $file.\n"
    if [ $(ls $log_dir | wc -w) -gt 1 ]; then
	pause
    fi
done
