#!/bin/sh -e

##########################################################################
#   Title:
#       lpjs-restart
#
#   Section:
#       8
#
#   Synopsis:
#       lpjs restart
#       
#   Description:
#       lpjs restarts lpjs_compd and lpjs_dispatchd, if they are enabled
#       as system services.  To start and stop these daemons manually,
#       see lpjs-ad-hoc(8).
#
#       Methods for restarting system services differ greatly depending
#       on the operating system.  lpjs restart frees the user from these
#       differences and from typing in complex commands in some cases.
#       
#   Arguments:
#       None
#       
#   Returns:
#       0 upon success, non-zero error codes otherwise
#
#   See also:
#       lpjs-admin(8), lpjs-start(8), lpjs-stop(8),
#       lpjs-compd-enable(8), lpjs-dispatchd-enable(8),
#       
#   History:
#   Date        Name        Modification
#   2024-05     Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

# Prevent user from running a Trojan as root in the case their account
# was compromised
absolute="$(which $0)"
# Don't count on -e being set at this point
if ! auto-file-secure "$absolute"; then
    exit 1
fi

if ! auto-root-check $0; then
    printf "Root "
    # exec quotes '$absolute --flag', causing usage error
    # Assigning to cmd works around the problem
    cmd="$absolute $@"
    exec su -m root -c "$cmd"
fi

lpjs stop || true
sleep 2
lpjs start
