#!/bin/sh -e

##########################################################################
#   Title:
#       lpjs-stop
#
#   Section:
#       8
#
#   Synopsis:
#       lpjs stop
#       
#   Description:
#       lpjs stops lpjs_compd and lpjs_dispatchd, if they are enabled
#       as system services.  To start and stop these daemons manually,
#       see lpjs-ad-hoc(8).
#
#       Methods for stoping system services differ greatly depending
#       on the operating system.  lpjs stop frees the user from these
#       differences and from typing in complex commands in some cases.
#       
#   Arguments:
#       None
#       
#   Returns:
#       0 upon success, non-zero error codes otherwise
#
#   See also:
#       lpjs-admin(8), lpjs-restart(8), lpjs-start(8),
#       lpjs-compd-enable(8), lpjs-dispatchd-enable(8),
#       
#   History:
#   Date        Name        Modification
#   2024-05     Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

# Prevent user from running a Trojan as root in the case their account
# was compromised
absolute="$(which $0)"
# Don't count on -e being set at this point
if ! auto-file-secure "$absolute"; then
    exit 1
fi

if ! auto-root-check $0; then
    printf "Root "
    # exec quotes '$absolute --flag', causing usage error
    # Assigning to cmd works around the problem
    cmd="$absolute $@"
    exec su -m root -c "$cmd"
fi

if [ $(uname) = Darwin ]; then
    set -x
    if [ -e /Library/LaunchDaemons/org.pkgsrc.lpjs_dispatchd.plist ]; then
	launchctl bootout system /Library/LaunchDaemons/org.pkgsrc.lpjs_dispatchd.plist || true
    fi

    if [ -e /Library/LaunchDaemons/org.pkgsrc.lpjs_compd.plist ]; then
	launchctl bootout system /Library/LaunchDaemons/org.pkgsrc.lpjs_compd.plist || true
    fi

elif [ $(uname) = DragonFly ] || [ $(uname) = FreeBSD ]; then
    if grep -E '^lpjs_dispatchd_enable=\"?[Yy][Ee][Ss]"?' /etc/rc.conf; then
	service lpjs_dispatchd stop
    fi
    
    if grep -E '^lpjs_compd_enable=\"?[Yy][Ee][Ss]"?' /etc/rc.conf; then
	service lpjs_compd stop
    fi

elif [ $(uname) = Linux ]; then
    if which systemctl; then
	set -x
	systemctl daemon-reload
	
	if systemctl | fgrep -q lpjs_dispatchd; then
	    systemctl stop lpjs_dispatchd
	fi
	
	if systemctl | fgrep -q lpjs_compd; then
	    systemctl stop lpjs_compd
	fi
    else
	printf "$0: Only systemd is currently supported.\n" >> /dev/stderr
	printf "Please consider adding support for other Linux init systems.\n"
	exit 1
    fi
    
elif [ $(uname) = NetBSD ]; then
    set -x
    if grep -E '^lpjs_dispatchd=\"?[Yy][Ee][Ss]"?' /etc/rc.conf; then
	service lpjs_dispatchd stop
    fi
    
    if grep -E '^lpjs_compd=\"?[Yy][Ee][Ss]"?' /etc/rc.conf; then
	service lpjs_compd stop
    fi

elif [ $(uname) = SunOS ]; then
    auto-unsupported-os $0

else
    auto-unsupported-os $0
fi
